controllers:
    resource: ../src/Presentation/Controller/
    type: attribute

app_logout:
    path: /logout
    methods: GET

shopping_list_actions:
    resource: ../src/Presentation/ShoppingList/Action
    type: attribute

shop_actions:
    resource: ../src/Presentation/Shop/Action
    type: attribute

recipe_actions:
    resource: ../src/Presentation/Recipe/Action
    type: attribute
