name: Deploy
on:
    push:
        branches:
            - main
jobs:
    build_front:
        name: Build Front (Vue)
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: DerYeger/yarn-setup-action@master
                with:
                    node-version: 14
            -   run: yarn build
    update_php:
        name: Connect to Server and update Symfony app
        runs-on: ubuntu-latest
        needs: build_front
        steps:
            -   name: execute
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    port: ${{ secrets.PORT }}
                    script: |
                        eval "$(ssh-agent -s)"
                        ssh-add ${{ secrets.RSA_LOCATION }}
                        cd ${{ secrets.HOSTING_DIR }}
                        git fetch origin main
                        git reset --hard origin/main
                        git clean -fdx
                        ln -s ./public private_html
                        echo ${{ secrets.ENV_LOCAL }} >> .env.local
                        echo ${{ secrets.HTACCESS }} >> ./public/.htaccess
                        php composer.phar install --no-dev
                        php bin/console cache:clear
                        php bin/console d:m:m
    deploy_front:
        name: Deploy frontend file
        runs-on: ubuntu-latest
        needs: update_php
        steps:
        -   name: copy built files
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                port: ${{ secrets.PORT }}
                key: ${{ secrets.SERVER_KEY }}
                source: "public/build"
                target: "${{ secrets.HOSTING_DIR }}/public"
